### ISSUE TITLE
Text Alignment issues with Firefox

### ISSUE THREAD

**Issue by spongedouglas** [CreateJS/EaselJS#650] opened 2015-08-13 17:01 UTC
Firefox appears to have two text alignment issues when using custom fonts, but one may only relate to Flash's usage of easel for canvas exports:

1. Text placed at y=0, inside a movieclip or on the main stage, will nudge up several pixels.

2. Firefox appears to render text at a slightly higher alignment in canvas across the board.

As my production team is producing animations with dynamic text fields, we can't circumvent this by converting to shapes.

Our work around is to avoid placing text fields at 0, and applying the following patch to the DisplayObject prototype in easel 0.8.1:

~~~
var is_firefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
if(is_firefox && createjs){
	createjs.DisplayObject.prototype.setTransform = function(x, y, scaleX, scaleY, rotation, skewX, skewY, regX, regY) {
		this.x = x || 0;
		this.y = y || 0;
		this.scaleX = scaleX == null ? 1 : scaleX;
		this.scaleY = scaleY == null ? 1 : scaleY;
		this.rotation = rotation || 0;
		this.skewX = skewX || 0;
		this.skewY = skewY || 0;
		this.regX = regX || 0;
		this.regY = regY || 0;
		
		/* ADJUST TEXT POSITION FOR FF */
		if(this.text){
			this.y += this.lineHeight*.3;
		}
		
		return this;
	};
}
~~~

**Comment by spongedouglas** [comment] 2015-08-13 23:03
Still working out the right amount to add to the y, but here's more detail on the y=0 bug.

Here is a screenshot showing how the dynamic text field "frameTwo_line3_300" renders in Firefox when its y is set to 0.
![text-y_0](https://cloud.githubusercontent.com/assets/7120511/9263709/5c979bd2-41ed-11e5-8f6e-f876bbedf821.png)

And the same field with y set to 1.
![text-y_1](https://cloud.githubusercontent.com/assets/7120511/9263708/5c971b6c-41ed-11e5-8f04-4b01e039aca3.png)

And here is the y=1 screenshot without adding anything to the y by hijacking setTransform:
![chrome-v-ff](https://cloud.githubusercontent.com/assets/7120511/9263769/ef79d0d2-41ed-11e5-92d1-e2fed8d4f4bc.png)
*Left: Chrome, Right: Firefox*

**Comment by gskinner** [comment] 2015-08-13 23:11
This is a duplicate of #235, which is unfortunately a documented bug in Firefox. The most reliable way to fix this is to change the text baseline, but that's a pain when exporting from Flash.

Voting or commenting on the bug might help, though its been open for a long time:
https://bugzilla.mozilla.org/show_bug.cgi?id=737852

If you do find a formula that is very reliable across fonts, let us know, we can help promote it to other users.

Closing for now since its a dupe, but feel free to reopen if you think there's a good reason.

**Comment by spongedouglas** [comment] 2015-08-13 23:18
@gskinner What about the y=0 aspect, which seems separate from the universal issue with Firefox+canvas+custom fonts? Or does that belong somewhere in the Flash team's domain with regard to how CreateJS is published in Flash Canvas documents?

**Comment by gskinner** [comment] 2015-08-13 23:21
Oops. I totally blanked on that issue, focusing on the one I've seen before. Very weird, especially since it occurs in MovieClips with their own transforms. I'll try to find a bit of time to test. Reopening.

**Comment by gskinner** [comment] 2015-08-13 23:29
Hmm. My quick test was unable to repro the y=0 issue in FF39 on OSX.

In the image below, the first two text fields are on the stage. The next two are in different MovieClips, one with the text field at y=0 and one at y=10. All of the lines are on the stage. I'm not seeing any difference between them.

Maybe there are other factors involved?

![screen shot 2015-08-13 at 5 27 01 pm](https://cloud.githubusercontent.com/assets/157128/9264182/94dc691c-41e0-11e5-9c23-5947e577777b.png)

**Comment by spongedouglas** [comment] 2015-08-13 23:40
Quite possibly. Did your test employ embedded fonts?

**Comment by gskinner** [comment] 2015-08-13 23:57
I get the same result (ie. no y=0 issue) when using Open Sans linked in from google fonts.

**Comment by Meychi** [comment] 2015-09-17 07:38
I had the same or similar issue with custom fonts, text drawn too high on Firefox and thus cutting text when cached. Instead of trying to manually fix it i created a patch based on the code here, overwriting the text positioning for Firefox. I tried this with four top google fonts and Fjalla One and in all cases it seems to produce consistent positioning with Chrome and IE. It's not pixel perfect but works for us. 

If Firefox get this fixed someday you can just remove the patch.

```
var firefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
if (firefox && createjs)
{
	createjs.Text.prototype._drawTextLine = function(ctx, text, y) 
	{
		// Adjust text position only if textBaseline is "top"
        if (this.textBaseline === "top") 
		{
			var lineHeight = this.lineHeight || this.getMeasuredLineHeight();
			y += lineHeight * 0.3;
		}
		// Chrome 17 will fail to draw the text if the last param is included but null, so we feed it a large value instead:
		if (this.outline) { ctx.strokeText(text, 0, y, this.maxWidth||0xFFFF); }
		else { ctx.fillText(text, 0, y, this.maxWidth||0xFFFF); }
	};
}
```

**Comment by pmnishab** [comment] 2015-10-16 11:17
Thx! spongedouglas. Your code works!

**Comment by lannymcnie** [comment] 2015-11-09 22:31
Closing this issue. We will probably not address FireFox's shifting - and it is documented in https://github.com/CreateJS/EaselJS/issues/235

If the remaining issue (y=0) still persists, feel free to re-open.

**Closed by lannymcnie** 2015-11-09 22:31 UTC
Labels: BrowserBug
