### ISSUE TITLE
animation is lagging on windows chrome only

### ISSUE THREAD

**Issue by ankitladhania** [CreateJS/EaselJS#579] opened 2015-03-14 18:11 UTC
i have created a website [Srijan'15] [1] which runs smoothly on IE and Firefox but is lagging very much on chrome.

What can i do to reduce the laggyness?

[1]:http://srijanism.org

**Comment by hayesmaker** [comment] 2015-04-06 19:17
it's laggy on firefox too. (at least on my core i7 mac book pro)... A quick look at the code suggests you probably should use a spritesheet to load all your images, it optimises animation performance, and reduces http requests.

I suspect the real cause of slow animation is caused by the vector drawn clouds... try removing them and see if speed improves.... if you want to use them you can build a spritesheet at runtime using SpriteSheetBuilder.

**Comment by lannymcnie** [comment] 2015-04-07 15:39
Closing this, as it isn't an issue with the library. I recommend posting to StackOverflow if you have specific questions about how to get better performance.

**Closed by lannymcnie** 2015-04-07 15:39 UTC
