### ISSUE TITLE
Documentation typo: Rectangle pad() method is misnamed extend() in the API docs

### ISSUE THREAD

**Issue by madcalf** [CreateJS/EaselJS#629] opened 2015-06-03 12:29 UTC
Just noticing that there are 2 extend() functions listed under the EJS Rectangle's methods. Based on the link to the source, looks like the second one should actually be pad()?

**Comment by lannymcnie** [comment] 2015-06-03 13:34
Duplicate of #625, which has been fixed. New documentation has not been pushed to the site yet. Thanks for the report!

**Closed by lannymcnie** 2015-06-03 13:34 UTC
