### ISSUE TITLE
0.8 cache no longer displays

### ISSUE THREAD

**Issue by bmanderscheid** [CreateJS/EaselJS#566] opened 2015-02-16 21:21 UTC
When caching a container or sprite, the display object does not show up when adding to stage.  Consequently, SpriteSheetBuilder is not working either.

**Comment by gskinner** [comment] 2015-02-16 21:24
It works in all my tests and examples. Can you provide more info?

**Comment by gskinner** [comment] 2015-02-16 21:26
For example:
http://www.createjs.com/Demos/EaselJS/Cache
http://www.createjs.com/Demos/EaselJS/Filters
Both use `cache`, and display fine for me.

**Comment by bmanderscheid** [comment] 2015-02-16 21:30
I worked my way back to this b/c SpriteSheetBuilder doesnt seem to be working when adding frames using cached containers.  Even this simple example below doesnt seem to be working

var car = new createjs.Sprite(carSS, "white");
stage.addChild(car); // JUST FINE

var car = new createjs.Sprite(carSS, "white");
car.cache(0, 0, 400, 200);
stage.addChild(car); // DOES NOT SHOW UP 

I've tried with all display objects, Shape works though.

**Comment by TheJasonReynolds** [comment] 2015-02-16 21:31
I can confirm the issue, I don't have a live example but for instance I
have a class:

(function (window) {
    window.game = window.game || {};
    function TrashCan(cantype) {
        this.Container_constructor();
        this.canType = cantype;
        this.setup();
    }

    var p = TrashCan.prototype = createjs.extend(TrashCan,
createjs.Container);



    p.canType = null;
    p.bg = null;
    p.boundries = null;

    p.setup = function () {
        this.bg = new createjs.Sprite(game.assets.spritesheet, "trashcan-"
+ this.canType);
        var w = this.bg.getBounds().width;
        var h = this.bg.getBounds().height;
        this.addChild(this.bg);
       // this.bg.cache(0,0,w,h);
    };

    window.game.TrashCan = createjs.promote(TrashCan, "Container");

}(window));


If I uncomment out the "this.bg.cache" line -- nothing is displayed on the
stage.

In the same project, I have a background:
 this.panelBg = new createjs.Bitmap(game.assets.getAsset("bgGraphic"));
        game.stage.addChild(this.panelBg);

If I do a .cache() on that panelBg -- it no longer displayed on the stage.

**Comment by bmanderscheid** [comment] 2015-02-16 21:33
Links do not work in Chrome, I'll try what I have going in Safari

**Comment by gskinner** [comment] 2015-02-16 21:34
The links I provided work for me in Chrome 40 on OSX.

**Comment by gskinner** [comment] 2015-02-16 21:37
I'll test caching Sprite instances in a moment, but why are you doing that? Are you applying a filter?

**Comment by TheJasonReynolds** [comment] 2015-02-16 21:37
Sadly I don't have a 'trimmed down' project I can post for a sample.

In my case, caching anything except a Shape will cause the object to not
display on the shape.

**Comment by bmanderscheid** [comment] 2015-02-16 21:40
I'm on same for Chrome, my bad on that. the links are fine but my code still is broken.
I'm not doing the example I showed, I'm using containers in spritesheetbuilder for frames.  I just worked my way backwards to trouble shoot. Tried manually caching container first and it didnt show up on stage. Then I tried sprite......

**Comment by bmanderscheid** [comment] 2015-02-16 21:50
This works with 0.7.1, but not with 0.8


function createBaseCar() {
    var runtimeSS;
    var container = new createjs.Container();
    var s = new createjs.Sprite(shadowSS, "shadow01");
    var car = new createjs.Sprite(carSS, "aspenWhite01");
    container.addChild(s,car);
    runtimeSS = new createjs.SpriteSheetBuilder();
    runtimeSS.addFrame(container);
    runtimeSS.addAnimation("car", [0]);
    runtimeSS.on("complete", function (e) {
        completeCar = new createjs.Sprite(e.target.spriteSheet,"car");
        stage.addChild(completeCar);
    });
    runtimeSS.build();
}

**Comment by gskinner** [comment] 2015-02-16 21:56
Sounds like we're talking about two separate issues in this thread: caching & spritesheetbuilder. I am currently trying to reproduce the caching issue. We can come back to SSB.

I can't repro this issue. I updated the SpriteSheet_simple example to preload the image and then cache the resulting Sprite, and it works fine in all browsers. If someone can create a JSFiddle that demonstrates the issue, I'd be happy to take a look at it, but for now, this is UTR. Please make sure you are preloading your images, too - caching a Sprite that's using an unloaded image will obviously result in a blank cache.

I'll take a look at the SpriteSheetBuilder as well, but it would help a lot if you could isolate the issue. All of our SSB examples work fine in 0.8.0, so I know it's not a general problem.

**Comment by TheJasonReynolds** [comment] 2015-02-16 21:58
I'll get working code I can actually post showing the cache problem when I
can.

**Comment by bmanderscheid** [comment] 2015-02-16 22:01
Sorry to jump around there.  I ultimately want to use the SpriteSheetBuilder class, which I assume is caching container objects passed into addFrame().  I figured the cache was the root of the issue.  
I'm using PreloadJS for all assets before building anything, so they are definitely loaded.  
I'll continue to play with it and hopefully can be more helpful.

**Comment by gskinner** [comment] 2015-02-16 22:03
@bmanderscheid No, SSB does not use `cache`. I just tested your scenario, and was similarly UTR. Again, I updated the SpriteSheet_simple example to preload the image, then added this code:
````
var grant = new createjs.Sprite(spriteSheet, "run");
var container = new createjs.Container();
container.addChild(grant);

var ssb = new createjs.SpriteSheetBuilder();
ssb.addFrame(container, new createjs.Rectangle(0,0,165,292));
var ss = ssb.build();

var sprite = new createjs.Sprite(ss, 0);
````

The Sprite shows correctly.

**Comment by gskinner** [comment] 2015-02-16 22:05
Please confirm you are both preloading your images. If you continue to see either issue, please create a JSFiddle that reproduces it in as simple a manner as possible, and let me know what browser you are seeing it in.

I am unable to reproduce either issue in any of the browsers listed above, so I'm closing this for now. Please reopen if you are able to provide a repro case. Thanks!

**Closed by gskinner** 2015-02-16 22:05 UTC
Labels: UTR

**Comment by bmanderscheid** [comment] 2015-02-16 22:27
queue = new createjs.LoadQueue(false);

OK, this gets it to work.

**Comment by gskinner** [comment] 2015-02-16 22:32
Is this testing off a server? If so, were you passing the image instance, or the url into the sprite sheet data?

If the latter, then I could see you running into a possible problem. The browser cache isn't super reliable when it comes to XHR loading. By the way, be sure to check out the new SpriteSheetLoader in PreloadJS - it lets you define your spritesheet data externally as a json file, and manages loading the related images automatically, returning a SpriteSheet instance as the result.

**Comment by bmanderscheid** [comment] 2015-02-16 22:39
I'm using localhost.  I'm using TexturePacker to build the files, and loading all json and pngs via PreloadJS before doing anything.  I didnt know about SpriteSheetLoader in PreloadJS, but I'll check it out and see if its something that will help in this project.  The SpriteSheetBuilder is gonna make this project go so smoothly :).
Thanks for the help.  ONE MORE THING:  should I cache containers before adding them to frames in SpriteSheetBuilder?
Thanks!

**Comment by gskinner** [comment] 2015-02-16 22:55
Caching just runs a normal draw onto an offscreen canvas. From that point on, that canvas can be quickly drawn instead of the original (hopefully much more complex) content.

So, if you're only ever going to draw once after doing a cache, it's actually better not to cache, because you may as well just draw directly onto the main canvas. It save memory (no extra offscreen canvas), and time (the offscreen canvas doesn't need to be drawn back).

In your case, if that container is only being used to draw a frame in a SpriteSheetBuilder, then there's no advantage to cache it ahead of time. The SSB will only draw the container once, when it renders the frame to the sprite sheet "image" (in this case, a canvas).

Hope that helps.

**Comment by bmanderscheid** [comment] 2015-02-16 23:01
perfect, thanks!
