### ISSUE TITLE
Would you build filename without version number

### ISSUE THREAD

**Issue by x09326** [CreateJS/EaselJS#807] opened 2016-10-13 06:01 UTC
Hi, I'm a member of [cdnjs](https://cdnjs.com/). This lib had already been hosted in cdnjs.
But it's hard to automatically update for this lib because of the naming scheme. 
So I prefer not to name files with the version number. (e.g., "easeljs-0.8.2.min.js" becomes "easeljs.min.js)

Thanks.
https://github.com/cdnjs/cdnjs/issues/8766
https://github.com/cdnjs/cdnjs/issues/9145
https://github.com/cdnjs/cdnjs/pull/9265

**Comment by hilts-vaughan** [comment] 2016-10-13 13:16
Why are you trying to auto update? This will cause grief if breaking
changes or bugs creep in.

**Comment by lannymcnie** [comment] 2016-10-13 15:15
Duplicate of #785. We are considering this.

**Closed by lannymcnie** 2016-10-13 15:15 UTC
Labels: duplicate

**Comment by x09326** [comment] 2016-10-14 03:59
@lannymcnie Thanks!

**Comment by x09326** [comment] 2016-10-14 04:02
@hilts-vaughan 
Why does auto-update cause grief?
We just set up auto-update config that update the version automatically.
Then we don't need to update the version of this lib when this lib update in the future.

**Comment by mateddy** [comment] 2016-12-27 05:11
@x09326 Auto-update might break old version compatibility. Production sites would love to pin a specific version rather than an auto-updated version.
