### ISSUE TITLE
CreateJS sometimes renders content out of place when rendered using Chrome 64.0.3282.119 

### ISSUE THREAD

**Issue by mjonkman** [CreateJS/EaselJS#938] opened 2018-02-02 00:21 UTC
When rendering complex layouts, CreateJS will occassionally render the content incorrectly for a split second before snapping the content into its correct position. This only occurs on Chrome 64.0.3282.119. Similar behavior is not scene on other browsers and prior version of Chrome in the 63.x.x.x series.

I've attached a screen shot of the issue occuring as well as a zipped quicktime movie of it happening.

![ninja_chrome_glitch_snapshot](https://user-images.githubusercontent.com/13684303/35710307-bcbe7a3a-0784-11e8-829a-ba1bac86c9a3.png)

[ninja_chrome_glitch.zip](https://github.com/CreateJS/EaselJS/files/1687657/ninja_chrome_glitch.zip)

We have not yet found a workaround for this issue. 

It only appears to occur with really heavy content where the browser struggles to render the content.

This occurred on Windows 10.

**Comment by 1le** [comment] 2018-02-04 11:03
Experiencing a very similar issue on mobile versions of Chrome 64. It seems that bounding boxes are not calculated correctly.

**Comment by lannymcnie** [comment] 2018-02-07 21:43
Could be a duplicate of https://github.com/CreateJS/EaselJS/issues/937

Canvas size exceeds 65536 pixels, starts causing some wacky issues! Chrome 64 bug.

**Comment by lannymcnie** [comment] 2018-11-21 17:03
Does this still persist with Chrome 65+? I am closing this, feel free to open if it still persists.

**Closed by lannymcnie** 2018-11-21 17:03 UTC
Labels: BrowserBug
