### ISSUE TITLE
Matrix2D.decompose() can't change 'rotation' property when skewX/skewY(0/0) = NaN

### ISSUE THREAD

**Issue by taiga** [CreateJS/EaselJS#939] opened 2018-02-22 05:20 UTC
When skewX and skewY are 0, delta becomes NaN, so I think it should add workaround code.

https://github.com/CreateJS/EaselJS/blob/v1.0.2/src/easeljs/geom/Matrix2D.js#L480-L484

**Comment by lannymcnie** [comment] 2018-11-21 22:37
Duplicate of #847.

**Closed by lannymcnie** 2018-11-21 22:37 UTC
Labels: bug
