### ISSUE TITLE
 How to use some images in SpriteSheet?  (SpriteStage)

### ISSUE THREAD

**Issue by iRomano** [CreateJS/EaselJS#695] opened 2015-11-24 13:53 UTC
How to use some images in SpriteSheet?  
images: [image1, image2, images3, ...]
If you use multiple images, the animation is played only the first picture (image1).
Yes, i set index image in frames
I use SpriteStage.
Is use simple Stage - all ok. But i want use SpriteStage

**Comment by iRomano** [comment] 2015-11-24 13:55
Yes, i set index image in frames

**Comment by MannyC** [comment] 2015-11-24 17:44
You cannot, at least currently.  SpriteStage uses a webgl renderer.  It only loads one image into the GPUs memory at a time, so a decision was made to only allow sprites with a single image to avoid performance issues caused by new images continually being pushed to the gpu

**Comment by lannymcnie** [comment] 2016-10-28 17:09
The beta "StageGL" (available in the stagegl-beta branch) should handle this (in theory).

**Comment by lannymcnie** [comment] 2016-10-28 17:17
Confirmed that StageGL does support it. https://github.com/CreateJS/EaselJS/tree/StageGL-beta

Closing this bug. We will not add this support to the deprecated SpriteStage.

**Closed by lannymcnie** 2016-10-28 17:17 UTC
Labels: FOL, question
